#!/usr/bin/env python3
"""
calibrate_judge.py — Task 2a analysis: is DeepSeek's taste the user's taste?

Inputs:
  judge-pairs.json       (generated by gen_judge_pairs.py — includes judge scores)
  judge-user-labels.json (downloaded from judge-calibration.html — user picks)

Method:
  1. AGREEMENT RATE (headline): for each pair, does the user's pick match the
     judge's higher-scored title? 100% = perfect agreement; 50% = coin flip.
     This is the robust measure at ~200 pairs — Elo per-title is noise-dominated
     when most titles appear once.
  2. ELO CORRELATION (supporting): convert pairwise wins to Elo, correlate the
     user's derived scores against DeepSeek's judge scores, restricted to titles
     with >= 2 appearances so ratings have a chance to converge.
  3. Print the decision table from the brief.

The brief's decision table (on correlation r):
  r >= 0.7   -> judge is a faithful stand-in; proceed to Task 2 at scale
  r 0.4-0.7  -> usable but biased; proceed, ensemble a 2nd model
  r < 0.4    -> WRONG TEACHER. STOP. Do not build the 5,000-label dataset.

Agreement-rate mapping (for the headline, since r is Elo-noisy at this N):
  >= 0.80 -> faithful stand-in   (near-coin-flip only on the close pairs)
  0.65-0.80 -> usable but biased
  < 0.65 -> wrong teacher

Usage: python tools/calibrate_judge.py [path-to-judge-user-labels.json]
"""

import json
import math
import os
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAIRS_PATH = os.path.join(ROOT, "judge-pairs.json")
DEFAULT_LABELS = os.path.join(ROOT, "judge-user-labels.json")

K_ELO = 32.0
PASSES = 20


def pearson(xs, ys):
    n = len(xs)
    if n < 3:
        return float("nan"), n
    mx, my = statistics.mean(xs), statistics.mean(ys)
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    dx = math.sqrt(sum((x - mx) ** 2 for x in xs))
    dy = math.sqrt(sum((y - my) ** 2 for y in ys))
    if dx == 0 or dy == 0:
        return float("nan"), n
    return num / (dx * dy), n


def compute_elo(pairs, by_id):
    """Iterative Elo over usable comparisons. Returns {lower_title: rating}."""
    elo = {}

    def rating(t):
        return elo.setdefault(t.lower(), 1500.0)

    def expected(a, b):
        return 1.0 / (1.0 + 10 ** ((b - a) / 400.0))

    for _ in range(PASSES):
        for pid, label in by_id.items():
            p = pairs.get(pid)
            if not p:
                continue
            choice = label.get("choice")
            if choice not in ("a", "b"):
                continue
            a, b = rating(p["titleA"]), rating(p["titleB"])
            ea, eb = expected(a, b), expected(b, a)
            sa = 1.0 if choice == "a" else 0.0
            elo[p["titleA"].lower()] = a + K_ELO * (sa - ea)
            elo[p["titleB"].lower()] = b + K_ELO * ((1 - sa) - eb)
    return elo


def main():
    labels_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_LABELS

    if not os.path.exists(PAIRS_PATH):
        print(f"ERROR: {PAIRS_PATH} not found — run tools/gen_judge_pairs.py first.")
        sys.exit(1)
    if not os.path.exists(labels_path):
        print(f"ERROR: {labels_path} not found.")
        print("       Open judge-calibration.html, label the pairs, download the JSON.")
        sys.exit(1)

    with open(PAIRS_PATH, encoding="utf-8") as fh:
        pairs_data = json.load(fh)
    with open(labels_path, encoding="utf-8") as fh:
        labels = json.load(fh)

    pairs = {p["id"]: p for p in pairs_data["pairs"]}
    by_id = {l["id"]: l for l in labels}

    # ---- 1. Agreement rate (headline) ----
    agree = 0
    total = 0
    close_agree = 0
    close_total = 0
    for pid, label in by_id.items():
        p = pairs.get(pid)
        if not p:
            continue
        choice = label.get("choice")
        if choice not in ("a", "b"):
            continue
        total += 1
        judge_higher = "a" if p["judgeScoreA"] >= p["judgeScoreB"] else "b"
        if choice == judge_higher:
            agree += 1
        if abs(p["judgeScoreA"] - p["judgeScoreB"]) <= 15:
            close_total += 1
            if choice == judge_higher:
                close_agree += 1

    agreement = agree / total if total else float("nan")
    close_agreement = close_agree / close_total if close_total else float("nan")

    print("=" * 70)
    print("  JUDGE CALIBRATION — user pairwise picks vs DeepSeek judge scores")
    print("=" * 70)
    print(f"  Pairs in tool        : {len(pairs)}")
    print(f"  Labels provided      : {len(labels)}")
    print(f"  Usable comparisons   : {total}")
    print(f"  Agreement rate       : {agreement:.1%}  (coin flip = 50%)" if total else "  Agreement rate: n/a")
    if close_total:
        print(f"  Agreement on close   : {close_agreement:.1%}  (judge gap <= 15 — where disagreement shows)")

    if total < 30:
        print("\n  WARNING: fewer than 30 usable comparisons — numbers are noise.")
        print("  Finish more pairs before trusting this.")

    # ---- 2. Elo correlation on well-connected titles ----
    elo = compute_elo(pairs, by_id)
    judge_by_title = {}
    for p in pairs.values():
        judge_by_title.setdefault(p["titleA"].lower(), p["judgeScoreA"])
        judge_by_title.setdefault(p["titleB"].lower(), p["judgeScoreB"])

    # Count appearances per title so we can restrict to >= 2.
    from collections import Counter
    appearances = Counter()
    for p in pairs.values():
        appearances[p["titleA"].lower()] += 1
        appearances[p["titleB"].lower()] += 1

    xs, ys = [], []
    for title_low, elo_rating in elo.items():
        if title_low in judge_by_title and appearances[title_low] >= 2:
            xs.append(elo_rating)
            ys.append(judge_by_title[title_low])
    r, n = pearson(xs, ys)

    print(f"\n  Elo correlation (titles with >=2 comparisons): "
          f"r = {r:+.3f} (n={n})" if not math.isnan(r)
          else "  Elo correlation: n too small")

    # ---- 3. Decision table (brief thresholds on r; agreement mapping) ----
    print("\n" + "-" * 70)
    # Primary: agreement rate. Fallback: Elo r.
    if total >= 30 and not math.isnan(agreement):
        if agreement >= 0.80:
            verdict = "FAITHFUL STAND-IN"
            action = "Judge is a faithful stand-in. Proceed to Task 2 — scale to 5,000 labels."
        elif agreement >= 0.65:
            verdict = "USABLE, BUT BIASED"
            action = "Proceed, but ensemble a second model (GPT-4o / Claude) and average scores."
        else:
            verdict = "WRONG TEACHER — STOP"
            action = "Do NOT build the 5,000-label dataset. The rubric needs rewriting, or human/revealed-preference labels must carry more weight."
    elif not math.isnan(r):
        if r >= 0.7:
            verdict = "FAITHFUL STAND-IN"
            action = "Judge is a faithful stand-in. Proceed to Task 2 — scale to 5,000 labels."
        elif r >= 0.4:
            verdict = "USABLE, BUT BIASED"
            action = "Proceed, but ensemble a second model (GPT-4o / Claude) and average scores."
        else:
            verdict = "WRONG TEACHER — STOP"
            action = "Do NOT build the 5,000-label dataset. The rubric needs rewriting, or human/revealed-preference labels must carry more weight."
    else:
        verdict = "INSUFFICIENT DATA"
        action = "Label more pairs (target >= 100 usable) and re-run."

    print(f"  VERDICT : {verdict}")
    print(f"  ACTION  : {action}")
    print("-" * 70)

    report_path = os.path.join(ROOT, "judge-calibration-report.json")
    with open(report_path, "w", encoding="utf-8") as fh:
        json.dump({
            "agreement_rate": agreement if not math.isnan(agreement) else None,
            "close_agreement_rate": close_agreement if not math.isnan(close_agreement) else None,
            "elo_r": r if not math.isnan(r) else None,
            "elo_n": n,
            "pairs": len(pairs), "usable": total,
            "verdict": verdict, "action": action,
        }, fh, indent=2)
    print(f"\n  Report: {report_path}")


if __name__ == "__main__":
    main()
